# Before running main program, install dependencies
using Pkg
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("Parameters")
Pkg.add("FastGaussQuadrature")
Pkg.add("SmolyakApprox")
Pkg.add("LinearAlgebra")
Pkg.add("Profile")
Pkg.add("Revise")
Pkg.add("UnPack")
Pkg.add("StructArrays")
Pkg.add("Interpolations")
Pkg.add("ForwardDiff")
Pkg.add("ProgressMeter")
Pkg.add("NLsolve")
Pkg.add("JLD")
Pkg.add("Printf")
Pkg.add("Plots")
Pkg.add("Dates")
Pkg.add("LaTeXStrings")
Pkg.add("MKL")
Pkg.add("BenchmarkTools")